{{- if eq .Values.apimgr.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.apimgr.name }}
  name: {{ .Values.apimgr.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.apimgr.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.apimgr.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: {{ .Values.global.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ .Values.apimgr.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ .Values.apimgr.name }}
              topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - {{ .Values.global.gwdir }}/posix/bin/start-emt-instance
        env:
        - name: GW_DIR
          value: {{ .Values.global.gwdir }}
        - name: GW_TRACE_DIR
          value: {{ .Values.global.gwdir }}/groups/topologylinks/emt-group-emt-service/trace
        - name: CASS0
          value: {{ .Values.cassandra.host0 }}
        - name: EMT_ANM_HOSTS
          value: {{ .Values.anm.name }}-int:{{ .Values.anm.trafficPort }}
        - name: EMT_HEAP_SIZE_MB
          value: "{{ .Values.apimgr.emt_heap_size_mb }}"
        - name: APIGW_LOG_TRACE_TO_FILE
          value: "{{ .Values.apimgr.logTraceToFile }}"
        - name: APIGW_LOG_TRACE_JSON_TO_STDOUT
          value: "{{ .Values.apimgr.logTraceJSONtoSTDOUT }}"
        - name: APIGW_LOG_OPENTRAFFIC_OUTPUT
          value: "{{ .Values.apimgr.logOpenTrafficOutput }}"
        - name: EMT_DEPLOYMENT_ENABLED
          value: "{{ .Values.emtDeployment.enabled }}"
        image: {{ .Values.global.dockerRegistry }}/{{ .Values.apimgr.imageName }}:{{ .Values.apigw.imageTag }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        name: {{ .Values.apimgr.name }}
        ports:
        - containerPort: {{ .Values.apimgr.trafficPort }}
          protocol: TCP
{{- if eq .Values.quotas.enabled true }}
        resources:
          limits:
            memory: "2Gi"
            cpu: 2
          requests:
            memory: "1.5Gi"
            cpu: 1.5
{{- end }}
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: k8sprobe
              value: readiness.{{ .Values.apimgr.name }}
            path: /healthcheck
            port: {{ .Values.apimgr.openPort }}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: k8sprobe
              value: liveness.{{ .Values.apimgr.name }}
            path: /healthcheck
            port: {{ .Values.apimgr.openPort }}
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      initContainers:
      - name: init1
        image: {{ .Values.global.initImageTag }}
        command: ['sh', '-c', 'until nc -w 3 -v {{ .Values.cassandra.host0 }} 9042; do echo waiting for {{ .Values.cassandra.host0 }}; sleep 2; done;']
      # - name: init2
      #   image: {{ .Values.global.initImageTag }}
      #   command: ['sh', '-c', 'until nc -w 3 -v {{ .Values.cassandra.host1 }} 9042; do echo waiting for {{ .Values.cassandra.host1 }}; sleep 2; done;']
      # - name: init3
      #   image: {{ .Values.global.initImageTag }}
      #   command: ['sh', '-c', 'until nc -w 3 -v {{ .Values.cassandra.host2 }} 9042; do echo waiting for {{ .Values.cassandra.host2 }}; sleep 2; done;']
{{- if eq .Values.mysql.enabled true }}
      - name: init4
        image: {{ .Values.global.initImageTag }}
        command: ['sh', '-c', 'until nc -w 3 -v {{ .Values.mysql.hostname }} 3306; do echo waiting for {{ .Values.mysql.hostname }}; sleep 2; done;']
{{- end }}
      - name: init5
        image: {{ .Values.global.initImageTag }}
        command: ['sh', '-c', 'until nc -w 3 -v {{ .Values.anm.name }}-int {{ .Values.anm.trafficPort }}; do echo waiting for anm-int; sleep 2; done;']
      - name: init6
        image: {{ .Values.global.initImageTag }}
        command: ['sh', '-c', 'until nc -w 3 -v {{ .Values.apimgmt.name }}-int {{ .Values.apimgmt.trafficPort }}; do echo waiting for apimgmt; sleep 2; done;']
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
{{- end }}
